import Employee from '../config/Schema/employee';
import Clinic from '../config/Schema/clinic';
import utils from '../utils/utils';

/**
 * generateCustomId
 * generates simplified Id for application use
 * ObjectId generated by MongoDB won't be practical.
 * */

async function generateEmpCustomId(filter) {
  const count = await Employee.countDocuments(filter);
  const customID = `EMP${(count + 1).toString().padStart(3, '0')}`;
  return customID;
}

const empController = {
  postNew: async (req, res) => {
    const firstName = req.body ? req.body.first : null;
    const lastName = req.body ? req.body.last : null;
    const otherName = req.body ? req.body.middle : null;
    const dOB = req.body ? req.body.dob : null;
    const gender = req.body ? req.body.gender : null;
    const contact = req.body ? req.body.mobile : null;
    const role = req.body ? req.body.role : null;
    const email = req.body ? req.body.email : null;
    const _password = req.body ? req.body.password : null;
    const repassword = req.body ? req.body.repassword : null;
    const clinicId = req.session.clinic.id;
    if (!firstName || !lastName) {
      res.status(400).json({ error: 'Employee Name is missing' });
      return;
    }
    if (!role) {
      res.status(400).json({ error: 'Employee role is required' });
      return;
    }
    if (!email) {
      res.status(400).json({ error: 'Employee Email is missing' });
      return;
    }
    if (!_password) {
      res.status(400).json({ error: 'Employee Password is missing' });
      return;
    }
    if (_password !== repassword) {
      res.status(404).json({ error: 'Passwords do not match' });
      return;
    }

    console.log(dOB);
    const password = utils.hashPassword(_password);
    const employeeID = await generateEmpCustomId({ clinicId });

    try {
      // check if clinic exists
      const existingEmp = await Employee.findOne({ $and: [{ clinicId }, { email }] });
      if (!existingEmp) {
        const newEmp = await Employee.create({
          employeeID,
          firstName,
          lastName,
          otherName,
          dOB,
          gender,
          contact,
          role,
          email,
          password,
          clinicId,
        });
        console.log('New employee created:', newEmp.employeeID);
        res.redirect('/clinic/dashboard');
      } else {
        res.status(400).json({ error: 'Employee Already exists' });
      }
    } catch (err) {
      res.status(500).json({ error: `${err}` });
    }
  },

  getShow: async (req, res) => {
    // get employee by req.params.id (employee._id)
    const employeeId = req.params.id;
    const clinicId = req.session.clinic.id;
    try {
      const employee = await Employee.findById(employeeId);
      if (employee.clinicId === clinicId) {
        const result = {
          id: employee.employeeID,
          name: `${employee.firstName} ${employee.lastName}`,
        };
        res.send(result);
      }
    } catch (err) {
      res.status(500).json({ error: err });
    }
  },

  getIndex: async (req, res) => {
    // get employees and if query, get by firstName or,
    // lastName or, role and page number for pagination
    try {
      // Extract query parameters
      const {
        employeeID, firstName, lastName, role, page,
      } = req.query;

      // Define query conditions based on clinicId
      const clinicId = req.session.clinic.id;
      const queryConditions = { clinicId };

      // Add additional query conditions based on provided parameters
      const orConditions = [];
      if (employeeID) orConditions.push({ employeeID });
      if (firstName) orConditions.push({ firstName });
      if (lastName) orConditions.push({ lastName });
      if (role) orConditions.push({ role });

      if (orConditions.length > 0) {
        queryConditions.$or = orConditions;
      }

      // Pagination
      const pageSize = 10; // Number of employees per page
      const pageNumber = parseInt(page, 10) || 1; // Current page number

      // Fetch employees based on query conditions and pagination
      const employees = await Employee.find(queryConditions)
        .skip((pageNumber - 1) * pageSize)
        .limit(pageSize);

      const results = employees.map((emp) => ({
        id: emp.employeeID,
        name: `${emp.firstName} ${emp.lastName}`,
      }));
      res.status(200).json(results);
    } catch (err) {
      console.error('Failed to get employees:', err);
      res.status(500).json({ error: 'Failed to get employees' });
    }
  },

  postEmployeeLogIn: async (req, res) => {
    const email = req.body ? req.body.email : null;
    const password = req.body ? req.body.password : null;

    // validate email and password
    if (!email) {
      res.status(400).json({ error: 'email required' });
      return;
    }
    if (!password) {
      res.status(400).json({ error: 'password required' });
      return;
    }

    // authenticate login
    // check if clinic exists in db
    try {
      const employee = await Employee.findOne({ email });
      if (!employee) {
        res.render('custom404Employee');
        return;
      }
      const isValid = utils.checkPassword(password, employee.password);
      if (!isValid) {
        res.status(401).json({ message: 'check email or password' });
        return;
      }
      // store employee session as object within clinic session
      let currentDate = new Date();
      let hours = currentDate.getUTCHours();
      let minutes = currentDate.getUTCMinutes();
      console.log(currentDate, hours, minutes);
      req.session.clinic.employee = {
        id: employee._id.toString(),
        loginTime: `${hours}:${minutes}`,
      };
      res.redirect('/employee/dashboard');
    } catch (err) {
      res.status(500).json({ error: `${err}` });
    }
  },

  getEmployee: async (req, res) => {
    if(!req.session) {
      res.redirect('/clinic/dashboard/login');
      return;
    }
    const clinicId = req.session.clinic.id;
    const clinic = await Clinic.findById(clinicId);
    const { clinicName } = clinic;
    const { id, loginTime } = req.session.clinic.employee;
    const employee = await Employee.findById(id);
    const { employeeID, firstName, otherName, lastName, role } = employee;
    const fullName = `${firstName} ${otherName} ${lastName}`;
    res.render('employeeDashboard', {
      clinicName,
      employeeID,
      fullName,
      role,
      loginTime
    });
  },

  postLogOut: (req, res) => {
    if (req.session.clinic && req.session.clinic.employee) {
      delete req.session.clinic.employee;
    }
    req.session.clinic ? res.redirect('/clinic/dashboard') : res.status(500).json({ error: 'Error' });
  },
};

module.exports = empController;
