import Examination from '../config/Schema/examination';
import Patient from '../config/Schema/patient';
import utils from '../utils/utils';

/**
 * generatePatientCustomId
 * generates simplified Id for application use
 * ObjectId generated by MongoDB won't be practical.
 * */

async function generatePatientCustomId(filter) {
  const count = await Patient.countDocuments(filter);
  const customID = `P${(count + 1).toString().padStart(3, '0')}`;
  return customID;
}

const patientController = {
  postNew: async (req, res) => {
    const firstName = req.body ? req.body.first : null;
    const otherName = req.body ? req.body.middle : null;
    const lastName = req.body ? req.body.last : null;
    const gender = req.body ? req.body.gender : null;
    const dOB = req.body ? req.body.dob : null;

    const contact = req.body ? req.body.mobile : null;
    const occupation = req.body ? req.body.occupation : null;
    const email = req.body ? req.body.email : null;
    const maritalStatus = req.body ? req.body.marital : null;
    const clinicId = req.session.clinic.id;
    if (!firstName || !lastName) {
      res.status(400).json({ error: 'Patient Name is missing' });
      return;
    }
    if (!gender) {
      res.status(400).json({ error: 'Choose Gender' });
      return;
    }
    if (!contact) {
      res.status(400).json({ error: 'Patient contact is missing' });
      return;
    }
    if (!occupation) {
      res.status(400).json({ error: 'Patient occupation is missing' });
      return;
    }

    const patientID = await generatePatientCustomId(clinicId);

    try {
      // check if clinic exists
      const filter = {
        $and: [
          { firstName },
          { lastName },
          { gender },
          { contact },
          { occupation },
          { clinicId },
        ],
      };
      const existingPatient = await Patient.findOne(filter);
      if (!existingPatient) {
        const patient = await Patient.create({
          patientID,
          firstName,
          lastName,
          otherName,
          dOB,
          gender,
          contact,
          email,
          maritalStatus,
          occupation,
          clinicId,
        });
        console.log('new Patient created:', patient.patientID);
        res.redirect('/employee/dashboard');
      } else {
        res.status(400).json({ error: 'Patient Already exists' });
      }
    } catch (err) {
      res.status(500).json({ error: `${err}` });
    }
  },

  getPatientForm: (req, res) => {
    res.render('register_patient');
  },

  getShow: async (req, res) => {
    // get patient by req.params.id (patient._id)
    const patientId = req.params.id;
    const clinicId = req.session.clinic.id;
    try {
      const patient = await Patient.findById(patientId);
      if (patient.clinicId === clinicId) {
        const result = {
          id: patient.patientID,
          name: `${patient.firstName} ${patient.lastName}`,
        };
        res.send(result);
      }
    } catch (err) {
      res.status(500).json({ error: err });
    }
  },

  getIndex: async (req, res) => {
    // get patient and if query, get by patientID, firstName or,
    // lastName or gender or contact
    // and page number for pagination
    try {
      // Extract query parameters
      const {
        patientID, firstName, lastName, page, contact, gender, occupation,
      } = req.query;

      // Define query conditions based on clinicId
      const clinicId = req.session.clinic.id;
      const queryConditions = { clinicId };

      // Add additional query conditions based on provided parameters
      const orConditions = [];
      if (patientID) orConditions.push({ patientID });
      if (firstName) orConditions.push({ firstName });
      if (lastName) orConditions.push({ lastName });
      if (contact) orConditions.push({ contact });
      if (gender) orConditions.push({ gender });
      if (occupation) orConditions.push({ occupation });

      if (orConditions.length > 0) {
        queryConditions.$or = orConditions;
      }

      // Pagination
      const pageSize = 10; // Number of employees per page
      const pageNumber = parseInt(page, 10) || 1; // Current page number

      // Fetch employees based on query conditions and pagination
      const patients = await Patient.find(queryConditions)
        .skip((pageNumber - 1) * pageSize)
        .limit(pageSize);

      const results = patients.map((patient) => ({
        id: patient.patientID,
        name: `${patient.firstName} ${patient.lastName}`,
        age: utils.calculateAge(patient.dOB) + 'years',
        gender: patient.gender,
        occupation: patient.occupation,
        contact: `${patient.contact}`
      }));
      res.render('patients', {
        results,
      });
    } catch (err) {
      console.error('Failed to get patients:', err);
      res.status(500).json({ error: 'Failed to get patients' });
    }
  },

  // getStats: endpoint to retrieve number of patients registered
  // a particular day and number of examinations done
  getStats: async (req, res) => {
  const clinicId = req.session.clinic.id;
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const tomorrow = new Date(today.getTime() + 24 * 60 * 60 * 1000);

  try {
    const patientCount = await Patient.countDocuments({
      clinicId: clinicId,
      createdAt: {
        $gte: today, // Greater than or equal to the start of the day
        $lt: tomorrow, // Less than the start of the next day
      },
    });
    console.log(patientCount);
    const examCount = await Examination.countDocuments({
      clinicId: clinicId,
      createdAt: {
        $gte: today, // Greater than or equal to the start of the day
        $lt: tomorrow, // Less than the start of the next day
      },
    });
    console.log(examCount);  

    res.status(200).json({
      Patients: patientCount,
      Examination: examCount,
    });
  } catch (err) {
    console.log('Failed to retrieve patient and exam count', err);
    res.status(500).json({ error: 'Failed' });
  }
  },

  // gets checkin with query params
  getPatients: async (req, res) => {
    try {
      const clinicId = req.session.clinic.id;
      const queryString = req.query.queryString || null;
      const queryOption = req.query.queryOption || null;
      const filter = { clinicId };
      // If both queryString and queryOption are provided, add them to the filter
      if (queryString && queryOption) {
          const regex = new RegExp(queryString, 'i');
          filter[queryOption] = { $regex: regex };
      } else if (queryString) {
          // If only queryString is provided, search across all fields
          const regex = new RegExp(queryString, 'i');
          filter.$or = Object.keys(Patient.schema.paths).filter(key => key !== '_id' && key !== '__v').map(key => ({ [key]: { $regex: regex } }));
      }
      const patients = await Patient.find(filter);
      console.log(patients);
      res.json(patients);
    } catch (err) {
      console.log(err);
      res.status(500).json({ error: `error searching patient ${err}` });
    }
  },
};

module.exports = patientController;
